# ============================================================
# One-click setup: generate random secrets -> clone/build -> start -> open dashboard
# Usage: right-click "Run with PowerShell", or in cmd:
#   powershell -NoProfile -ExecutionPolicy Bypass -File setup.ps1
# ============================================================
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

# 1. Docker check
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host '[ERROR] docker not found. Install and start Docker Desktop first.' -ForegroundColor Red
    exit 1
}
docker info *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Host '[ERROR] Docker daemon is not running. Start Docker Desktop first.' -ForegroundColor Red
    exit 1
}

# 2. Generate .env with random secrets (no manual edit needed)
if (-not (Test-Path "$root\.env")) {
    function New-RandomHex([int]$len = 32) {
        $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'.ToCharArray()
        -join (1..$len | ForEach-Object { $chars | Get-Random })
    }
    $adminPwd = New-RandomHex 24
    $accessKey = 'sk-' + (New-RandomHex 24)
    $session  = New-RandomHex 32
    @"
# Generated by setup.ps1. Do not edit by hand.
# Enter account keys (Codex / OpenCode / Command Code) in the web dashboard instead:
#   http://localhost:8888
CC_ADAPTER_ADMIN_PASSWORD=$adminPwd
CC_ADAPTER_ACCESS_KEY=$accessKey
SESSION_SECRET=$session
"@ | Set-Content -Path "$root\.env" -Encoding ASCII
    Write-Host '[2/4] Generated random secrets into .env (no manual edit needed)' -ForegroundColor Green
} else {
    Write-Host '[2/4] .env exists, keep it'
}

# 3. Clone command-code-adapter
if (-not (Test-Path "$root\cc-adapter\pyproject.toml")) {
    Write-Host '[3/4] Cloning command-code-adapter ...'
    git clone --depth 1 https://github.com/dgqyushen/command-code-adapter.git "$root\cc-adapter"
    if ($LASTEXITCODE -ne 0) { Write-Host '[ERROR] git clone failed. Check network and retry.' -ForegroundColor Red; exit 1 }
} else {
    Write-Host '[3/4] cc-adapter already exists'
}

# 4. Build and start
Write-Host '[4/4] docker compose up -d --build ...'
docker compose -f "$root\docker-compose.yml" up -d --build
if ($LASTEXITCODE -ne 0) { Write-Host '[ERROR] compose up failed. See logs above.' -ForegroundColor Red; exit $LASTEXITCODE }

Start-Sleep -Seconds 3
docker compose -f "$root\docker-compose.yml" ps

Write-Host ''
Write-Host '============================================================' -ForegroundColor Cyan
Write-Host ' Dashboard (add accounts) : http://localhost:8888' -ForegroundColor Cyan
Write-Host ' new-api panel            : http://localhost:3001' -ForegroundColor Cyan
Write-Host ' Unified API endpoint     : http://localhost:3000/v1' -ForegroundColor Cyan
Write-Host ' CC adapter panel         : http://localhost:8080/admin' -ForegroundColor Cyan
Write-Host '============================================================' -ForegroundColor Cyan
Write-Host 'Next: open the dashboard, add Codex / OpenCode / Command Code'
Write-Host 'accounts, then click "Apply all". Opening dashboard ...'
Start-Process 'http://localhost:8888'